//package com.datacloud.cybertron.service.ds.msg
//
//import java.util.Date
//
//package object execution {
//
//  case class TongdunInput(indivName: Option[String],
//                          indivID: Option[String],
//                          indivPhone: Option[String])
//
//  case class TongdunOutput(td_antifraudScore: Option[Long],
//                           td_finalDecision: Option[String],
//                           td_applyTime: Option[String],
//                           td_reportTime: Option[String],
//                           td_deviceInfo_deviceId: Option[String],
//                           td_geoIp_ip: Option[String],
//                           td_geoIp_county: Option[String],
//                           td_geoIp_country: Option[String],
//                           td_geoIp_city: Option[String],
//                           td_geoIp_lip: Option[String],
//                           td_geoIp_isp: Option[String],
//                           td_geoIp_province: Option[String],
//                           td_geoIp_latitude: Option[BigDecimal],
//                           td_geoIp_longitude: Option[BigDecimal],
//                           td_geoTrueip_ip: Option[String],
//                           td_geoTrueip_county: Option[String],
//                           td_geoTrueip_country: Option[String],
//                           td_geoTrueip_city: Option[String],
//                           td_geoTrueip_lip: Option[String],
//                           td_geoTrueip_isp: Option[String],
//                           td_geoTrueip_province: Option[String],
//                           td_geoTrueip_latitude: Option[BigDecimal],
//                           td_geoTrueip_longitude: Option[BigDecimal],
//                           td_addressDetect_idCardAddress: Option[String],
//                           td_addressDetect_trueIpAddress: Option[String],
//                           td_addressDetect_wifiAddress: Option[String],
//                           td_addressDetect_cellAddress: Option[String],
//                           td_addressDetect_bankCardAddress: Option[String],
//                           td_addressDetect_mobileAddress: Option[String],
//                           td_riskItems_0_itemId: Option[Long],
//                           td_riskItems_0_itemName: Option[String],
//                           td_riskItems_0_riskLevel: Option[String],
//                           td_riskItems_0_group: Option[String],
//                           td_riskItems_0_itemDetail_discreditTimes: Option[java.util.ArrayList[Long]],
//                           td_riskItems_0_itemDetail_overdueDetails_0_overdueAmountRange: Option[java.util.ArrayList[String]],
//                           td_riskItems_0_itemDetail_overdueDetails_0_overdueCount: Option[java.util.ArrayList[Long]],
//                           td_riskItems_0_itemDetail_overdueDetails_0_overdueDayRange: Option[java.util.ArrayList[String]],
//                           td_riskItems_0_itemDetail_overdueDetails_0_overdueTime: Option[java.util.ArrayList[java.util.ArrayList[Date]]],
//                           td_riskItems_0_itemDetail_platformCount: Option[Long],
//                           td_riskItems_0_itemDetail_platformDetail_0_x: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_platformDetailDimension_0_count: Option[java.util.ArrayList[Long]],
//                           td_riskItems_0_itemDetail_platformDetailDimension_0_detail_0_x: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_platformDetailDimension_0_dimension: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_highRiskAreas_0_x: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_hitListDatas_0_x: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_fraudType: Option[java.util.ArrayList[String]],
//                           td_riskItems_0_itemDetail_frequencyDetailList_0_data_0_x: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_frequencyDetailList_0_detail: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_crossFrequencyDetailList_0_data: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_crossFrequencyDetailList_0_detail: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_crossEventDetailList_0_data: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_crossEventDetailList_0_detail: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_description: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_fraudType: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_hitTypeDisplayname: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_type: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_fuzzyDetailHits_0_fraudType: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_fuzzyDetailHits_0_fuzzyIdNumber: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_fuzzyDetailHits_0_fuzzyName: Option[java.util.ArrayList[java.util.ArrayList[String]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_fraudType: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_name: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_age: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_gender: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_province: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_filingTime: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_courtName: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_executionDepartment: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_duty: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_situation: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_discreditDetail: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_executionBase: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_caseNumber: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_executionNumber: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]],
//                           td_riskItems_0_itemDetail_namelistHitDetails_0_courtDetails_0_executionStatus: Option[java.util.ArrayList[java.util.ArrayList[java.util.ArrayList[String]]]]
//                          )
//
//  case class TongdunPreloan(requestId: String,
//                            upstreamId: String,
//                            upstreamRequestId: String,
//                            downstreamRequestId: Option[String],
//                            templateName: String,
//                            requestTime: Long,
//                            requestResultTime: Long,
//                            responseResultTime: Long,
//                            dataSourceId: Long,
//                            expiredTime: Long,
//                            source: String,
//                            status: String,
//                            comment: Option[String],
//                            input: TongdunInput,
//                            output: TongdunOutput)
//
//}
