/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datacloud.report.dataflow.protocol.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class City extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -112640686698575353L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"City\",\"namespace\":\"com.datacloud.report.dataflow.protocol.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"population\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String name;
  @Deprecated public long population;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public City() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param population The new value for population
   */
  public City(java.lang.String name, java.lang.Long population) {
    this.name = name;
    this.population = population;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return population;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.String)value$; break;
    case 1: population = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'population' field.
   * @return The value of the 'population' field.
   */
  public java.lang.Long getPopulation() {
    return population;
  }

  /**
   * Sets the value of the 'population' field.
   * @param value the value to set.
   */
  public void setPopulation(java.lang.Long value) {
    this.population = value;
  }

  /**
   * Creates a new City RecordBuilder.
   * @return A new City RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.City.Builder newBuilder() {
    return new com.datacloud.report.dataflow.protocol.avro.City.Builder();
  }

  /**
   * Creates a new City RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new City RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.City.Builder newBuilder(com.datacloud.report.dataflow.protocol.avro.City.Builder other) {
    return new com.datacloud.report.dataflow.protocol.avro.City.Builder(other);
  }

  /**
   * Creates a new City RecordBuilder by copying an existing City instance.
   * @param other The existing instance to copy.
   * @return A new City RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.City.Builder newBuilder(com.datacloud.report.dataflow.protocol.avro.City other) {
    return new com.datacloud.report.dataflow.protocol.avro.City.Builder(other);
  }

  /**
   * RecordBuilder for City instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<City>
    implements org.apache.avro.data.RecordBuilder<City> {

    private java.lang.String name;
    private long population;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datacloud.report.dataflow.protocol.avro.City.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.population)) {
        this.population = data().deepCopy(fields()[1].schema(), other.population);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing City instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datacloud.report.dataflow.protocol.avro.City other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.population)) {
        this.population = data().deepCopy(fields()[1].schema(), other.population);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.City.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.City.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'population' field.
      * @return The value.
      */
    public java.lang.Long getPopulation() {
      return population;
    }

    /**
      * Sets the value of the 'population' field.
      * @param value The value of 'population'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.City.Builder setPopulation(long value) {
      validate(fields()[1], value);
      this.population = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'population' field has been set.
      * @return True if the 'population' field has been set, false otherwise.
      */
    public boolean hasPopulation() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'population' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.City.Builder clearPopulation() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public City build() {
      try {
        City record = new City();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.population = fieldSetFlags()[1] ? this.population : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
