/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datacloud.report.dataflow.protocol.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Person extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6866376030106469951L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"com.datacloud.report.dataflow.protocol.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"date\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"timeMillis\",\"type\":\"int\",\"logicalType\":\"time-millis\"},{\"name\":\"timestampMillis\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"duration\",\"type\":{\"type\":\"fixed\",\"name\":\"PersonDuration\",\"size\":12},\"logicalType\":\"duration\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String name;
  @Deprecated public int date;
  @Deprecated public int timeMillis;
  @Deprecated public long timestampMillis;
  @Deprecated public com.datacloud.report.dataflow.protocol.avro.PersonDuration duration;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Person() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param date The new value for date
   * @param timeMillis The new value for timeMillis
   * @param timestampMillis The new value for timestampMillis
   * @param duration The new value for duration
   */
  public Person(java.lang.String name, java.lang.Integer date, java.lang.Integer timeMillis, java.lang.Long timestampMillis, com.datacloud.report.dataflow.protocol.avro.PersonDuration duration) {
    this.name = name;
    this.date = date;
    this.timeMillis = timeMillis;
    this.timestampMillis = timestampMillis;
    this.duration = duration;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return date;
    case 2: return timeMillis;
    case 3: return timestampMillis;
    case 4: return duration;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.String)value$; break;
    case 1: date = (java.lang.Integer)value$; break;
    case 2: timeMillis = (java.lang.Integer)value$; break;
    case 3: timestampMillis = (java.lang.Long)value$; break;
    case 4: duration = (com.datacloud.report.dataflow.protocol.avro.PersonDuration)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.Integer getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.Integer value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'timeMillis' field.
   * @return The value of the 'timeMillis' field.
   */
  public java.lang.Integer getTimeMillis() {
    return timeMillis;
  }

  /**
   * Sets the value of the 'timeMillis' field.
   * @param value the value to set.
   */
  public void setTimeMillis(java.lang.Integer value) {
    this.timeMillis = value;
  }

  /**
   * Gets the value of the 'timestampMillis' field.
   * @return The value of the 'timestampMillis' field.
   */
  public java.lang.Long getTimestampMillis() {
    return timestampMillis;
  }

  /**
   * Sets the value of the 'timestampMillis' field.
   * @param value the value to set.
   */
  public void setTimestampMillis(java.lang.Long value) {
    this.timestampMillis = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public com.datacloud.report.dataflow.protocol.avro.PersonDuration getDuration() {
    return duration;
  }

  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(com.datacloud.report.dataflow.protocol.avro.PersonDuration value) {
    this.duration = value;
  }

  /**
   * Creates a new Person RecordBuilder.
   * @return A new Person RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.Person.Builder newBuilder() {
    return new com.datacloud.report.dataflow.protocol.avro.Person.Builder();
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Person RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.Person.Builder newBuilder(com.datacloud.report.dataflow.protocol.avro.Person.Builder other) {
    return new com.datacloud.report.dataflow.protocol.avro.Person.Builder(other);
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Person instance.
   * @param other The existing instance to copy.
   * @return A new Person RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.Person.Builder newBuilder(com.datacloud.report.dataflow.protocol.avro.Person other) {
    return new com.datacloud.report.dataflow.protocol.avro.Person.Builder(other);
  }

  /**
   * RecordBuilder for Person instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Person>
    implements org.apache.avro.data.RecordBuilder<Person> {

    private java.lang.String name;
    private int date;
    private int timeMillis;
    private long timestampMillis;
    private com.datacloud.report.dataflow.protocol.avro.PersonDuration duration;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datacloud.report.dataflow.protocol.avro.Person.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timeMillis)) {
        this.timeMillis = data().deepCopy(fields()[2].schema(), other.timeMillis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestampMillis)) {
        this.timestampMillis = data().deepCopy(fields()[3].schema(), other.timestampMillis);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Person instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datacloud.report.dataflow.protocol.avro.Person other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timeMillis)) {
        this.timeMillis = data().deepCopy(fields()[2].schema(), other.timeMillis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestampMillis)) {
        this.timestampMillis = data().deepCopy(fields()[3].schema(), other.timestampMillis);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.Integer getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder setDate(int value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder clearDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeMillis' field.
      * @return The value.
      */
    public java.lang.Integer getTimeMillis() {
      return timeMillis;
    }

    /**
      * Sets the value of the 'timeMillis' field.
      * @param value The value of 'timeMillis'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder setTimeMillis(int value) {
      validate(fields()[2], value);
      this.timeMillis = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timeMillis' field has been set.
      * @return True if the 'timeMillis' field has been set, false otherwise.
      */
    public boolean hasTimeMillis() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timeMillis' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder clearTimeMillis() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestampMillis' field.
      * @return The value.
      */
    public java.lang.Long getTimestampMillis() {
      return timestampMillis;
    }

    /**
      * Sets the value of the 'timestampMillis' field.
      * @param value The value of 'timestampMillis'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder setTimestampMillis(long value) {
      validate(fields()[3], value);
      this.timestampMillis = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestampMillis' field has been set.
      * @return True if the 'timestampMillis' field has been set, false otherwise.
      */
    public boolean hasTimestampMillis() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestampMillis' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder clearTimestampMillis() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public com.datacloud.report.dataflow.protocol.avro.PersonDuration getDuration() {
      return duration;
    }

    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder setDuration(com.datacloud.report.dataflow.protocol.avro.PersonDuration value) {
      validate(fields()[4], value);
      this.duration = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Person.Builder clearDuration() {
      duration = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Person build() {
      try {
        Person record = new Person();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.Integer) defaultValue(fields()[1]);
        record.timeMillis = fieldSetFlags()[2] ? this.timeMillis : (java.lang.Integer) defaultValue(fields()[2]);
        record.timestampMillis = fieldSetFlags()[3] ? this.timestampMillis : (java.lang.Long) defaultValue(fields()[3]);
        record.duration = fieldSetFlags()[4] ? this.duration : (com.datacloud.report.dataflow.protocol.avro.PersonDuration) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
