/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datacloud.report.dataflow.protocol.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(12)
@org.apache.avro.specific.AvroGenerated
public class PersonDuration extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = 1972283046209636241L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"PersonDuration\",\"namespace\":\"com.datacloud.report.dataflow.protocol.avro\",\"size\":12}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new PersonDuration */
  public PersonDuration() {
    super();
  }

  /**
   * Creates a new PersonDuration with the given bytes.
   * @param bytes The bytes to create the new PersonDuration.
   */
  public PersonDuration(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
