/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datacloud.report.dataflow.protocol.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Province extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9087914711257349999L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Province\",\"namespace\":\"com.datacloud.report.dataflow.protocol.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"area\",\"type\":\"double\"},{\"name\":\"cities\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"City\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"population\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String name;
  @Deprecated public double area;
  @Deprecated public java.util.List<com.datacloud.report.dataflow.protocol.avro.City> cities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Province() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param area The new value for area
   * @param cities The new value for cities
   */
  public Province(java.lang.String name, java.lang.Double area, java.util.List<com.datacloud.report.dataflow.protocol.avro.City> cities) {
    this.name = name;
    this.area = area;
    this.cities = cities;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return area;
    case 2: return cities;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.String)value$; break;
    case 1: area = (java.lang.Double)value$; break;
    case 2: cities = (java.util.List<com.datacloud.report.dataflow.protocol.avro.City>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'area' field.
   * @return The value of the 'area' field.
   */
  public java.lang.Double getArea() {
    return area;
  }

  /**
   * Sets the value of the 'area' field.
   * @param value the value to set.
   */
  public void setArea(java.lang.Double value) {
    this.area = value;
  }

  /**
   * Gets the value of the 'cities' field.
   * @return The value of the 'cities' field.
   */
  public java.util.List<com.datacloud.report.dataflow.protocol.avro.City> getCities() {
    return cities;
  }

  /**
   * Sets the value of the 'cities' field.
   * @param value the value to set.
   */
  public void setCities(java.util.List<com.datacloud.report.dataflow.protocol.avro.City> value) {
    this.cities = value;
  }

  /**
   * Creates a new Province RecordBuilder.
   * @return A new Province RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.Province.Builder newBuilder() {
    return new com.datacloud.report.dataflow.protocol.avro.Province.Builder();
  }

  /**
   * Creates a new Province RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Province RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.Province.Builder newBuilder(com.datacloud.report.dataflow.protocol.avro.Province.Builder other) {
    return new com.datacloud.report.dataflow.protocol.avro.Province.Builder(other);
  }

  /**
   * Creates a new Province RecordBuilder by copying an existing Province instance.
   * @param other The existing instance to copy.
   * @return A new Province RecordBuilder
   */
  public static com.datacloud.report.dataflow.protocol.avro.Province.Builder newBuilder(com.datacloud.report.dataflow.protocol.avro.Province other) {
    return new com.datacloud.report.dataflow.protocol.avro.Province.Builder(other);
  }

  /**
   * RecordBuilder for Province instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Province>
    implements org.apache.avro.data.RecordBuilder<Province> {

    private java.lang.String name;
    private double area;
    private java.util.List<com.datacloud.report.dataflow.protocol.avro.City> cities;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datacloud.report.dataflow.protocol.avro.Province.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.area)) {
        this.area = data().deepCopy(fields()[1].schema(), other.area);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cities)) {
        this.cities = data().deepCopy(fields()[2].schema(), other.cities);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Province instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datacloud.report.dataflow.protocol.avro.Province other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.area)) {
        this.area = data().deepCopy(fields()[1].schema(), other.area);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cities)) {
        this.cities = data().deepCopy(fields()[2].schema(), other.cities);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Province.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Province.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'area' field.
      * @return The value.
      */
    public java.lang.Double getArea() {
      return area;
    }

    /**
      * Sets the value of the 'area' field.
      * @param value The value of 'area'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Province.Builder setArea(double value) {
      validate(fields()[1], value);
      this.area = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'area' field has been set.
      * @return True if the 'area' field has been set, false otherwise.
      */
    public boolean hasArea() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'area' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Province.Builder clearArea() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cities' field.
      * @return The value.
      */
    public java.util.List<com.datacloud.report.dataflow.protocol.avro.City> getCities() {
      return cities;
    }

    /**
      * Sets the value of the 'cities' field.
      * @param value The value of 'cities'.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Province.Builder setCities(java.util.List<com.datacloud.report.dataflow.protocol.avro.City> value) {
      validate(fields()[2], value);
      this.cities = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cities' field has been set.
      * @return True if the 'cities' field has been set, false otherwise.
      */
    public boolean hasCities() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cities' field.
      * @return This builder.
      */
    public com.datacloud.report.dataflow.protocol.avro.Province.Builder clearCities() {
      cities = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Province build() {
      try {
        Province record = new Province();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.area = fieldSetFlags()[1] ? this.area : (java.lang.Double) defaultValue(fields()[1]);
        record.cities = fieldSetFlags()[2] ? this.cities : (java.util.List<com.datacloud.report.dataflow.protocol.avro.City>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
