/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datacloud.cybertron.service.dstemplate.client.indonesia;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClientDataInput extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1669579659236588255L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientDataInput\",\"namespace\":\"com.datacloud.cybertron.service.dstemplate.client.indonesia\",\"fields\":[{\"name\":\"indivID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"tenantId\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClientDataInput> ENCODER =
      new BinaryMessageEncoder<ClientDataInput>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClientDataInput> DECODER =
      new BinaryMessageDecoder<ClientDataInput>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClientDataInput> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClientDataInput> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClientDataInput>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClientDataInput to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClientDataInput from a ByteBuffer. */
  public static ClientDataInput fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String indivID;
  @Deprecated public java.lang.Long tenantId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClientDataInput() {}

  /**
   * All-args constructor.
   * @param indivID The new value for indivID
   * @param tenantId The new value for tenantId
   */
  public ClientDataInput(java.lang.String indivID, java.lang.Long tenantId) {
    this.indivID = indivID;
    this.tenantId = tenantId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return indivID;
    case 1: return tenantId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: indivID = (java.lang.String)value$; break;
    case 1: tenantId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'indivID' field.
   * @return The value of the 'indivID' field.
   */
  public java.lang.String getIndivID() {
    return indivID;
  }

  /**
   * Sets the value of the 'indivID' field.
   * @param value the value to set.
   */
  public void setIndivID(java.lang.String value) {
    this.indivID = value;
  }

  /**
   * Gets the value of the 'tenantId' field.
   * @return The value of the 'tenantId' field.
   */
  public java.lang.Long getTenantId() {
    return tenantId;
  }

  /**
   * Sets the value of the 'tenantId' field.
   * @param value the value to set.
   */
  public void setTenantId(java.lang.Long value) {
    this.tenantId = value;
  }

  /**
   * Creates a new ClientDataInput RecordBuilder.
   * @return A new ClientDataInput RecordBuilder
   */
  public static com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder newBuilder() {
    return new com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder();
  }

  /**
   * Creates a new ClientDataInput RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClientDataInput RecordBuilder
   */
  public static com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder newBuilder(com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder other) {
    return new com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder(other);
  }

  /**
   * Creates a new ClientDataInput RecordBuilder by copying an existing ClientDataInput instance.
   * @param other The existing instance to copy.
   * @return A new ClientDataInput RecordBuilder
   */
  public static com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder newBuilder(com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput other) {
    return new com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder(other);
  }

  /**
   * RecordBuilder for ClientDataInput instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientDataInput>
    implements org.apache.avro.data.RecordBuilder<ClientDataInput> {

    private java.lang.String indivID;
    private java.lang.Long tenantId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.indivID)) {
        this.indivID = data().deepCopy(fields()[0].schema(), other.indivID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tenantId)) {
        this.tenantId = data().deepCopy(fields()[1].schema(), other.tenantId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClientDataInput instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.indivID)) {
        this.indivID = data().deepCopy(fields()[0].schema(), other.indivID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tenantId)) {
        this.tenantId = data().deepCopy(fields()[1].schema(), other.tenantId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'indivID' field.
      * @return The value.
      */
    public java.lang.String getIndivID() {
      return indivID;
    }

    /**
      * Sets the value of the 'indivID' field.
      * @param value The value of 'indivID'.
      * @return This builder.
      */
    public com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder setIndivID(java.lang.String value) {
      validate(fields()[0], value);
      this.indivID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'indivID' field has been set.
      * @return True if the 'indivID' field has been set, false otherwise.
      */
    public boolean hasIndivID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'indivID' field.
      * @return This builder.
      */
    public com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder clearIndivID() {
      indivID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tenantId' field.
      * @return The value.
      */
    public java.lang.Long getTenantId() {
      return tenantId;
    }

    /**
      * Sets the value of the 'tenantId' field.
      * @param value The value of 'tenantId'.
      * @return This builder.
      */
    public com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder setTenantId(java.lang.Long value) {
      validate(fields()[1], value);
      this.tenantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tenantId' field has been set.
      * @return True if the 'tenantId' field has been set, false otherwise.
      */
    public boolean hasTenantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tenantId' field.
      * @return This builder.
      */
    public com.datacloud.cybertron.service.dstemplate.client.indonesia.ClientDataInput.Builder clearTenantId() {
      tenantId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClientDataInput build() {
      try {
        ClientDataInput record = new ClientDataInput();
        record.indivID = fieldSetFlags()[0] ? this.indivID : (java.lang.String) defaultValue(fields()[0]);
        record.tenantId = fieldSetFlags()[1] ? this.tenantId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClientDataInput>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClientDataInput>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClientDataInput>
    READER$ = (org.apache.avro.io.DatumReader<ClientDataInput>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
